CXX= c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98

SRCS= HumanA.cpp  HumanB.cpp  main.cpp  Weapon.cpp


NAME=Unnecessary_violence

all:$(NAME)

$(NAME):
	$(CXX) $(CXXFLAGS) $(SRCS) -o $(NAME)


fclean:
	rm -f $(NAME)

re: fclean all
