CXX= c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98

SRCS = main.cpp Zombie.cpp  newZombie.cpp randomChump.cpp

NAME = BraiiiiiiinnnzzzZ

all: $(NAME)

$(NAME): 
	$(CXX) $(CXXFLAGS) $(SRCS) -o $(NAME)


fclean:
	rm -f $(NAME)

re: fclean all
