CXX= c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98

SRCS= HumanA.cpp  HumanB.cpp  main.cpp  Weapon.cpp

OBJS=$(SRCS:.cpp=.o)

NAME=pr

all:$(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(NAME)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all
